version: '3'

services:
  node:
    build:
      context: ./rskj
    container_name: rskj-node
    image: rskj:latest
    ports:
      - "4444:4444"
      - "50505:50505/udp"

volumes: 
  rskj-database:
    
networks:
  json-proxy:
    driver: bridge