version: '3'

services:
  app:
    build: 
      context: ./dockerfile/rskj
      dockerfile: Dockerfile.Testnet
    networks:
        - json-proxy
    ports: 
      - "4444:4444"
      - "5050:5050"
      
networks:
  json-proxy:
    driver: bridge
