version: '3'

services:
  node:
    build: 
      context: ./dockerfile/rskj
      dockerfile: Dockerfile.Testnet
    networks:
        - json-proxy
    ports: 
      - "4444:4444"
      - "5050:5050"
    volumes:
      - "./rsk.log:/var/log/rsk/rsk.log"
      
networks:
  json-proxy:
    driver: bridge
