version: '3'

services:
  node:
    container_name: rskj-node
    build: 
      context: ./dockerfile/rskj
      dockerfile: Dockerfile.Testnet
    networks:
        - json-proxy
    ports: 
      - "4444:4444"
      - "5050:5050"
    volumes:
      - "./rsk.log:/var/log/rsk/rsk.log"
      - "db-rskj:/var/lib/rsk/database/testnet"

volumes: 
  db-rskj:
networks:
  json-proxy:
    driver: bridge
