version: '3'

services:
  node:
    build:
      context: ./rskj
    container_name: rskj-node
    image: rskj:latest
    networks: 
      - proxy
    ports:
      - "4444:4444"
      - "50505:50505/udp"
      - "50505:50505/tcp"

    volumes:
      - rskj-database:/var/lib/rsk/database
      - ./rsk.log:/var/log/rsk/rsk.log

volumes: 
  rskj-database:
    
networks:
  proxy:
    driver: bridge