[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.rskj.acme]
  email = "alejandro.drabenche@iovlabs.com"
  storage = "/acme.json"
  [certificatesResolvers.myresolver.acme.httpChallenge]
    entryPoint = "web"

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock" # De donde toma los providers
[log]
  level = "DEBUG"