version: '3'

services:
  reverse-proxy:
    container_name: json-reverse-proxy
    image: traefik:v2.3
    command: --api.insecure=true
    networks:
      - traefik-json-proxy
    ports:
      - "80:80"
    labels:
      - "traefik.http.routers.redirs.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.middlewares=test-auth"
      - "traefik.http.middlewares.test-auth.basicauth.usersFile=/usersFile"
    volumes:
      # Allow traefik to access docker api from the container
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./usersFile:/usersFile
    
  nginx:
    image: nginx
    networks:
      - traefik-json-proxy
    labels:
      - "traefik.http.routers.nginx.rule=Host(`httpd.docker.localhost`) || Path(`/traefik`) || Query(`foo=bar`)"
    
  app:
    build: 
      context: ./dockerfile
      dockerfile: Dockerfile
    networks:
        - traefik-json-proxy
    labels:
      - "traefik.http.routers.app.rule=Host(`app.docker.localhost`)"
      - "traefik.http.services.app.loadbalancer.server.port=8080"

networks:
  traefik-json-proxy:
    driver: bridge