[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.rskj.acme]
  email = "mail@domain.com"
  storage = "/acme.json"
  [certificatesResolvers.rskj.acme.httpChallenge]
    entryPoint = "web"

# Here, an average of 200 requests per minute is allowed.
# In addition, a burst of 10 requests is allowed.
[http.middlewares]
  [http.middlewares.test-ratelimit.rateLimit]
    average = 200
    period = 60
    burst = 10

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
[log]
  level = "INFO"

[pilot]
  token = "e907b219-be49-4c2e-85c2-862d1d82220b"

[experimental.plugins.rewritebody]
  modulename = "github.com/traefik/plugin-rewritebody"
  version = "v0.3.1"