[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.rskj.acme]
  email = "mail@example.com"
  storage = "/acme.json"
  [certificatesResolvers.rskj.acme.httpChallenge]
    entryPoint = "web"

[http.middlewares]
  [http.middlewares.test-ratelimit.rateLimit]
    average = 200
    period = 60
    burst = 10

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"

[experimental.plugins.forcedbody]
  modulename = "github.com/benoitg31/traefik-forced-plugin"
  version = "v1.0.2"
