[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.rskj.acme]
  email = "mail@domain.com"
  storage = "/acme.json"
  [certificatesResolvers.rskj.acme.httpChallenge]
    entryPoint = "web"

[http.routers.my-router]
    rule = "HostMethod(`GET`)"
    middlewares = ["rewrite-foo"]
    service = "rskj-node"

[http.middlewares]
  [http.middlewares.test-ratelimit.rateLimit]
    average = 200
    period = 60
    burst = 10

  [http.middlewares.rewrite-foo.plugin.rewritebody]
    lastModified = true
    [[http.middlewares.rewrite-foo.plugin.rewritebody.rewrites]]
      regex = "*"
      replacement = "Use POST"

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
[log]
  level = "INFO"

[experimental.plugins.rewritebody]
  modulename = "github.com/traefik/plugin-rewritebody"
  version = "v0.3.1"

[experimental.plugins.rco]
  moduleName = "github.com/Lepkem/traefik-plugin-response-code-override"
  version = "v0.0.3"