[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.rskj.acme]
  email = "alejandro.drabenche@iovlabs.org"
  storage = "/acme.json"
  [certificatesResolvers.rskj.acme.httpChallenge]
    entryPoint = "web"

[http.middlewares]
  [http.middlewares.test-ratelimit.rateLimit]
    average = 200
    period = 60
    burst = 10

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
[log]
  level = "INFO"

[experimental.plugins.traefik-forced-body-plugin]
  moduleName = "github.com/benoitg31/traefik-forced-body-plugin"
  version = "v0.1.4"
